Update x264 version.
Also, set $EXECTUTABLES variable.

R=bradnelson@google.com

Review URL: https://codereview.chromium.org/525043002

diff --git a/ports/x264/nacl.patch b/ports/x264/nacl.patch
--- a/ports/x264/nacl.patch
+++ b/ports/x264/nacl.patch
@@ -1,43 +1,49 @@
-diff -Naur x264-snapshot-20091023-2245/common/cpu.c x264-snapshot-20091023-2245.nacl/common/cpu.c
---- x264-snapshot-20091023-2245/common/cpu.c	2013-01-28 17:05:06.963624641 -0800
-+++ x264-snapshot-20091023-2245.nacl/common/cpu.c	2009-10-23 13:45:08.000000000 -0700
-@@ -67,7 +67,7 @@
+diff --git a/common/cpu.c b/common/cpu.c
+index 837de89..f2fa468 100644
+--- a/common/cpu.c
++++ b/common/cpu.c
+@@ -93,7 +93,7 @@ const x264_cpu_name_t x264_cpu_names[] =
      {"", 0},
  };
  
--#if (defined(ARCH_PPC) && defined(SYS_LINUX)) || (defined(ARCH_ARM) && !defined(HAVE_NEON))
-+#if (defined(ARCH_PPC) && defined(SYS_LINUX)) || (defined(ARCH_ARM) && !defined(HAVE_NEON) && !defined(__native_client__))
+-#if (ARCH_PPC && SYS_LINUX) || (ARCH_ARM && !HAVE_NEON)
++#if (ARCH_PPC && SYS_LINUX) || (ARCH_ARM && HAVE_ARMV6 && !HAVE_NEON)
  #include <signal.h>
  #include <setjmp.h>
  static sigjmp_buf jmpbuf;
-diff -Naur x264-snapshot-20091023-2245/configure x264-snapshot-20091023-2245.nacl/configure
---- x264-snapshot-20091023-2245/configure	2009-10-23 13:45:08.000000000 -0700
-+++ x264-snapshot-20091023-2245.nacl/configure	2012-01-27 13:38:51.496821868 -0800
-@@ -206,6 +206,11 @@
-     CFLAGS="$CFLAGS -DHAVE_MALLOC_H"
-     LDFLAGS="$LDFLAGS -lm"
-     ;;
-+  *nacl*)
-+    SYS="NACL"
-+    CFLAGS="$CFLAGS -DHAVE_MALLOC_H"
-+    LDFLAGS="$LDFLAGS -lm"
-+    ;;
-   cygwin*)
-     SYS="MINGW"
-     EXE=".exe"
-@@ -445,7 +450,14 @@
- elif [ $ARCH = ARM ]; then
-     # arm-gcc-4.2 produces incorrect output with -ffast-math
-     # and it doesn't save any speed anyway on 4.4, so disable it
--    CFLAGS="-O4 -fno-fast-math $CFLAGS"
-+    if [ "$SYS" = NACL ]; then
-+        # nacl gcc arm has known issue with -O4
-+        # TODO(sbc): remove this once this issue gets addressed:
-+        # https://code.google.com/p/nativeclient/issues/detail?id=3205
-+        CFLAGS="-O2 -fno-fast-math $CFLAGS"
-+    else
-+        CFLAGS="-O4 -fno-fast-math $CFLAGS"
+diff --git a/configure b/configure
+index 0a4cb94..2f84cc2 100755
+--- a/configure
++++ b/configure
+@@ -547,6 +547,16 @@ case $host_os in
+         LDFLAGSCLI="$LDFLAGSCLI -lshell32"
+         [ $compiler = GNU ] && RC="${RC-${cross_prefix}windres}" || RC="${RC-rc}"
+         ;;
++    *nacl*)
++        SYS="NACL"
++        define HAVE_MALLOC_H
++        if [[ $(basename ${CC}) =~ pnacl-* ]]; then
++            EXE=.pexe
++        else
++            EXE=.nexe
++        fi
++        libm="-lm"
++        ;;
+     sunos*|solaris*)
+         SYS="SunOS"
+         define HAVE_MALLOC_H
+@@ -773,11 +783,14 @@ ASFLAGS="$ASFLAGS -DSTACK_ALIGNMENT=$stack_alignment"
+ if [ $compiler = GNU ]; then
+     echo "int i[2] = {0x42494745,0}; double f[2] = {0x1.0656e6469616ep+102,0};" > conftest.c
+     $CC $CFLAGS conftest.c -c -o conftest.o 2>/dev/null || die "endian test failed"
++    # there is no pnacl-strings binary.
++    if [[ ! $(basename ${CC}) =~ pnacl-* ]]; then
+     if (${cross_prefix}strings -a conftest.o | grep -q BIGE) && (${cross_prefix}strings -a conftest.o | grep -q FPendian) ; then
+         define WORDS_BIGENDIAN
+     elif !(${cross_prefix}strings -a conftest.o | grep -q EGIB && ${cross_prefix}strings -a conftest.o | grep -q naidnePF) ; then
+         die "endian test failed"
+     fi
 +    fi
- else
-     CFLAGS="-O4 -ffast-math $CFLAGS"
  fi
+ 
+ # autodetect options that weren't forced nor disabled
